# Generated by Django 3.1 on 2021-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20210811_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='message',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_portfolio',
        ),
    ]
